package com.epul.ergosum.metier;

// Generated 24 avr. 2014 11:38:54 by Hibernate Tools 4.0.0

/**
 * ComporteId generated by hbm2java
 */
public class ComporteId implements java.io.Serializable {

	private int annee;
	private String numero;

	public ComporteId() {
	}

	public ComporteId(int annee, String numero) {
		this.annee = annee;
		this.numero = numero;
	}

	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComporteId))
			return false;
		ComporteId castOther = (ComporteId) other;

		return (this.getAnnee() == castOther.getAnnee())
				&& ((this.getNumero() == castOther.getNumero()) || (this
						.getNumero() != null && castOther.getNumero() != null && this
						.getNumero().equals(castOther.getNumero())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAnnee();
		result = 37 * result
				+ (getNumero() == null ? 0 : this.getNumero().hashCode());
		return result;
	}

}
